In [7]:
import pandas as pd

In [8]:
df = pd.read_json('samples/2023061719_20.json', lines=True)
df.head(5)

,artist,song,duration,ts,sessionId,auth,level,itemInSession,city,zip,state,userAgent,lon,lat,userId,lastName,firstName,gender,registration
0,Daryl Hall & John Oates,Don't Hold Back Your Love,313.88690,1661129304330,20857,Logged In,paid,20,Memphis,38135,TN,Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7....,-89.848559,35.238925,212,Morgan,Tenli,F,1655316754330
1,Wayne Newton,Silver Bells,191.37260,1661129331330,21068,Logged In,paid,10,Zimmerman,55398,MN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; r...,-93.610385,45.465616,300,Ortiz,Johnathan,M,1654970638330
2,Selena,I Could Fall In Love,278.30810,1661129352330,20213,Logged In,paid,28,Alhambra,91803,CA,"""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4...",-118.145959,34.074736,875,Cruz,William,M,1654748074330
3,Florence + The Machine,Falling,215.30077,1661129473330,20512,Logged In,free,3,Hazlehurst,31539,GA,Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) G...,-82.605344,31.831700,565,Johnson,Gaven,M,1655109594330
4,Rise Against,Entertainment,214.64770,1661129522330,21068,Logged In,paid,11,Zimmerman,55398,MN,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; r...,-93.610385,45.465616,300,Ortiz,Johnathan,M,1654970638330

In [9]:
df.describe()

,duration,ts,sessionId,itemInSession,zip,lon,lat,userId,registration
count,867.000000,8.670000e+02,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,8.670000e+02
mean,241.626655,1.661150e+12,19756.739331,19.366782,51424.573241,-93.988854,37.205068,455.868512,1.655149e+12
std,83.261950,1.153523e+07,2455.537104,19.634223,34452.330534,18.746323,5.214450,289.083582,3.587620e+08
min,21.655060,1.661129e+12,8028.000000,0.000000,1247.000000,-122.987330,26.112600,24.000000,1.654025e+12
25%,194.846890,1.661140e+12,20037.000000,4.000000,22003.000000,-118.084529,34.074736,212.000000,1.655106e+12
50%,229.041180,1.661150e+12,20785.000000,13.000000,44256.000000,-89.848559,37.058096,454.000000,1.655236e+12
75%,270.615050,1.661161e+12,21036.000000,29.500000,91001.000000,-77.215318,42.196388,641.000000,1.655415e+12
max,869.250200,1.661169e+12,21288.000000,96.000000,98027.000000,-70.288071,47.493732,996.000000,1.655492e+12

In [ ]:

# Count free vs paid in the 'level' column
level_counts = df['level'].value_counts()
print(level_counts)

level
paid    734
free    133
Name: count, dtype: int64

In [16]:
#unique values in userAgent column
user_agent_counts = df['userAgent'].value_counts()
print(user_agent_counts)

userAgent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2"                        123
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0                                                                        84
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"                                 79
"Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36"                                 65
Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20100101 Firefox/31.0                                                                               59
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:31.0) Gecko/20100101 Firefox/31.0                                                               57
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"                     49
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0                                                                        35
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36"                                 30
"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"                                 29
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko                                                                            28
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)                                                                         26
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36"                      26
"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"                                        25
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/7.0.5 Safari/537.77.4"                         24
"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36"                                 21
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36"                       16
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"                      11
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko                                                                            11
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/6.1.5 Safari/537.77.4"                         11
"Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53"     10
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"                      10
"Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"                                  8
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0                                                                     5
"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36"                                         4
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:31.0) Gecko/20100101 Firefox/31.0                                                                3
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.103 Safari/537.36"                                  3
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36"                                       3
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"                       2
Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0                                                                       2
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36"                        2
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36"                       2
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.59.10 (KHTML, like Gecko) Version/5.1.9 Safari/534.59.10"                        1
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/34.0.1847.116 Chrome/34.0.1847.116 Safari/537.36"        1
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36"        1
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0                                                                         1
Name: count, dtype: int64

In [17]:
# Count occurrences of each userId and display the top 10
top_user_ids = df['userId'].value_counts().head(10)
print(top_user_ids)

userId
539    87
784    64
26     58
411    54
950    49
595    40
534    34
151    33
366    27
300    27
Name: count, dtype: int64

In [ ]:
top_user_df = df[df['userId'].isin(top_user_ids)]
top_user_df.head(10)

In [21]:
# Print unique values for each column in top_user_df
for column in top_user_df.columns:
    print(f"Unique values in column '{column}':")
    print(top_user_df[column].unique())
    print()

Unique values in column 'artist':
['Hayley Westenra' 'The Offspring' 'The Smiths' 'Avenged Sevenfold'
 'Marisa Monte' 'The Wallflowers' 'Julie London' 'Midlake' 'Daft Punk'
 'Rammstein' 'Lifehouse' 'Miranda Lambert' 'Alabama' 'Tino Casal'
 'Dropkick Murphys' 'Jean Michel Jarre' 'Devendra Banhart' 'Philip Glass'
 'Daddy Yankee / Randy' 'Huey Lewis & The News' 'Cut Copy' 'The Rapture'
 'Sara Bareilles' 'Aisha Duo' 'Talking Heads']

Unique values in column 'song':
['Summer Fly' 'Genocide' 'The Headmaster Ritual' 'Unholy Confessions'
 'Lenda Das Sereias_ Rainha Do Mar' 'One Headlight' "Don't Worry 'Bout Me"
 'Roscoe' 'Human After All' 'Mutter' 'Blind' 'The House That Built Me'
 "I'm In A Hurry (And Don't Know Why)" 'Embrujada'
 'Johnny_ I Hardly Knew Ya' 'Bells' 'Cristobal' 'Northern Tibet'
 "Salgo Pa' La Calle" 'If This Is It' 'Saturdays'
 'Whoo! Alright - Yeah...Uh Huh.' 'Gravity' 'Beneath an Evening Sky'
 'Ruby Dear']

Unique values in column 'duration':
[219.76772 213.10649 294.97424 283.7677  250.06975 312.63303 155.95058
 286.85016 319.42484 268.56445 300.01587 236.61668 168.202   263.83627
 292.2575  227.26485 270.2624  202.50076 267.62405 234.31792 217.96526
 228.67546 233.3775  288.60037 230.29506]

Unique values in column 'ts':
[1661162401330 1661162620330 1661162833330 1661163127330 1661163410330
 1661163660330 1661163972330 1661164127330 1661164413330 1661164732330
 1661165000330 1661165300330 1661165536330 1661165704330 1661165967330
 1661166259330 1661166486330 1661166756330 1661166958330 1661167225330
 1661167459330 1661167676330 1661167904330 1661168137330 1661168425330]

Unique values in column 'sessionId':
[20971]

Unique values in column 'auth':
['Logged In']

Unique values in column 'level':
['paid']

Unique values in column 'itemInSession':
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 17 18 19 20 21 22 23 24
 25]

Unique values in column 'city':
['Redmond']

Unique values in column 'zip':
[97756]

Unique values in column 'state':
['OR']

Unique values in column 'userAgent':
['Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)']

Unique values in column 'lon':
[-121.216724]

Unique values in column 'lat':
[44.283326]

Unique values in column 'userId':
[49]

Unique values in column 'lastName':
['Moon']

Unique values in column 'firstName':
['Derriona']

Unique values in column 'gender':
['F']

Unique values in column 'registration':
[1655318266330]

In [ ]:
# Print unique userAgent values in top_user_df
print("Unique userAgent in top_user_df:")
print(top_user_df['userAgent'].unique())

Unique userIds in top_user_df:
['Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)']

In [ ]:
# Print unique state values in top_user_df
print("Unique states in top_user_df:")
print(top_user_df['state'].unique())

Unique states in top_user_df:
['OR']

In [24]:
# Count how many of the top 10 users are 'paid' and 'free'
top_user_level_counts = top_user_df['level'].value_counts()
print("Counts of 'paid' and 'free' for top 10 users:")
print(top_user_level_counts)

Counts of 'paid' and 'free' for top 10 users:
level
paid    25
Name: count, dtype: int64

In [25]:
# Count how many of the top 10 users are male versus female
top_user_gender_counts = top_user_df['gender'].value_counts()
print("Counts of male and female for top 10 users:")
print(top_user_gender_counts)

Counts of male and female for top 10 users:
gender
F    25
Name: count, dtype: int64